### ISSUE TITLE
Need documentation for when system says there’s no label

### ISSUE THREAD

**Issue by kgb1420** [Islandora-Collaboration-Group/icg_csv_import#13]
Problem: System was saying there’s no label
New objects were coming in, but with an icon and no title and no image
Fix: copy the title column and head it with the Key “LABEL.” Re-import.

**Comment by kgb1420** [comment]
This issue could also be related to the lack of the ICG Hooks module.

**Comment by McFateM** [comment]
Commit introduced warning message in the code.  The warnings look like this:

![screen shot 2016-10-14 at 3 13 52 pm](https://cloud.githubusercontent.com/assets/8472769/19401535/76bb37dc-9221-11e6-9f48-2875c3b93a6a.png)

**Comment by McFateM** [comment]
Commit https://github.com/Islandora-Collaboration-Group/icg_csv_import/commit/2fcb66865a961884f7ed34bd964d062ce6d3ea31 added additional guidance...

![screen shot 2016-10-14 at 3 22 46 pm](https://cloud.githubusercontent.com/assets/8472769/19401686/56577fe0-9222-11e6-8663-9c722da5bd13.png)
