### ISSUE TITLE
Proposal: Introduce more flexible xml attribute mapping to csv importer.

### ISSUE THREAD

**Issue by patdunlavey** [Islandora-Collaboration-Group/icg_csv_import#8]
Background: At the moment, an element attribute can be specified in the xpath for a column. E.g.
"/mods/name[@thing='something']"
"John Doe"

Proposal: Introduce more flexible xml attribute mapping to csv importer.
1. Permit more than one attribute to be specified:
   "/mods/name[@thing='something' and @anotherthing='something else']"
   "John Doe"
2. Permit attributes to be coded into the value:
   "/mods/name"
   "John Doe[@thing='something' and @anotherthing='something else']"
3. Support multiple values in a single column:
   "/mods/name"
   "John Doe[@thing='something' and @anotherthing='something else']|Jane Doe[@thing='something' and @anotherthing='something else']"
4. Support multiple values in multiple columns:
   "/mods/name[1]", "/mods/name[2]"
   "John Doe[@thing='something' and @anotherthing='something else']", "Jane Doe[@thing='something' and @anotherthing='something else']"

**Comment by McFateM** [comment]
Item 1, handling [@first='one' and @second='two' and @third='three'] syntax in the Xpath header, has been addressed and successfully tested (on a limited basis) in batch.inc within the 'development' branch of DigitalGrinnell/icg_csv_import.

Commit d198bd4 verified that this is working for Proposal 1 above.

Moving on to Proposal 2.

**Comment by McFateM** [comment]
Commit https://github.com/Islandora-Collaboration-Group/icg_csv_import/commit/7e30820270d85daed956c23c8f24c4778e03d151 changes are now working acceptably for Items 2, 3 and 4 above.   I'll be updating the README.md file to document these changes now.

**Comment by McFateM** [comment]
Commit https://github.com/Islandora-Collaboration-Group/icg_csv_import/commit/d8e3b721fd1c81bf62eff071608934ced50b866e documents changes made to resolve this issue.  I am closing the issue now.
