### ISSUE TITLE
Validation of xpath mapping in first row of CSV

### ISSUE THREAD

**Issue by MarthaTenney** [Islandora-Collaboration-Group/icg_csv_import#9]
When "CSV first row already contains the field mapping" is checked, some validation should be done on the CSV to ensure that it actually does contain xpath mapping. Currently it will import without throwing an error.

**Comment by McFateM** [comment]
Corrected in https://github.com/Islandora-Collaboration-Group/icg_csv_import/commit/309f72ab1000fa8ce899bb76687bda6dac407caa and https://github.com/Islandora-Collaboration-Group/icg_hooks/commit/09452455fd12398492e5f38bf1bb9654157ffdbb in icg_hooks.

Test outcomes include the following:

![screen shot 2016-10-14 at 10 38 48 am](https://cloud.githubusercontent.com/assets/8472769/19394466/e9dfdd9e-91fe-11e6-9c9b-b9bc9a39e6fc.png)
![screen shot 2016-10-14 at 10 45 00 am](https://cloud.githubusercontent.com/assets/8472769/19394469/ef223770-91fe-11e6-9604-65af64d561ca.png)
![screen shot 2016-10-14 at 11 00 14 am](https://cloud.githubusercontent.com/assets/8472769/19394473/f45f4782-91fe-11e6-988c-3399ac716444.png)

**Comment by McFateM** [comment]
I added the test data used above to the repository.  Should be good-to-go.
